import type { Theme } from "../types";

export const gearDefault: Theme = {
  id: "gear-default",
  name: "Gear Default",
  description: "Gear's signature teal palette",
  variants: {
    dark: {
      colors: {
        background: "#181c1f",
        foreground: "#e8ecef",
        card: "#1e2328",
        cardForeground: "#e8ecef",
        popover: "#1e2328",
        popoverForeground: "#e8ecef",
        primary: "#2dd4bf",
        primaryForeground: "#0c1a18",
        secondary: "#262c31",
        secondaryForeground: "#e8ecef",
        muted: "#262c31",
        mutedForeground: "#7a8a95",
        accent: "#262c31",
        accentForeground: "#e8ecef",
        destructive: "#f87171",
        border: "rgba(255,255,255,0.09)",
        input: "rgba(255,255,255,0.13)",
        ring: "#2dd4bf",
        sidebar: "#1e2328",
        sidebarForeground: "#e8ecef",
        sidebarPrimary: "#2dd4bf",
        sidebarPrimaryForeground: "#e8ecef",
        sidebarAccent: "#262c31",
        sidebarAccentForeground: "#e8ecef",
        sidebarBorder: "rgba(255,255,255,0.09)",
        sidebarRing: "#2dd4bf",
      },
      terminal: {
        background: "#181c1f",
        foreground: "#e8ecef",
        cursor: "#2dd4bf",
        cursorAccent: "#0c1a18",
        selection: "#2dd4bf33",
        ansi: [
          "#1e2328", "#f87171", "#4ade80", "#facc15",
          "#60a5fa", "#c084fc", "#2dd4bf", "#9ca3af",
          "#374151", "#fca5a5", "#86efac", "#fde68a",
          "#93c5fd", "#d8b4fe", "#5eead4", "#e8ecef",
        ],
      },
    },
    light: {
      colors: {
        background: "#eef1f3",
        foreground: "#1a2126",
        card: "#e6eaec",
        cardForeground: "#1a2126",
        popover: "#e6eaec",
        popoverForeground: "#1a2126",
        primary: "#0f766e",
        primaryForeground: "#eef1f3",
        secondary: "#d9dee1",
        secondaryForeground: "#1a2126",
        muted: "#d9dee1",
        mutedForeground: "#4a5a63",
        accent: "#ced4d8",
        accentForeground: "#1a2126",
        destructive: "#b91c1c",
        border: "#bfc8cc",
        input: "#bfc8cc",
        ring: "#0f766e",
        sidebar: "#e6eaec",
        sidebarForeground: "#1a2126",
        sidebarPrimary: "#0f766e",
        sidebarPrimaryForeground: "#eef1f3",
        sidebarAccent: "#d9dee1",
        sidebarAccentForeground: "#1a2126",
        sidebarBorder: "#bfc8cc",
        sidebarRing: "#0f766e",
      },
    },
  },
};
