import type { Theme } from "../types";

export const nord: Theme = {
  id: "nord",
  name: "Nord",
  description: "Arctic, north-bluish color palette",
  variants: {
    dark: {
      colors: {
        background: "#2e3440",
        foreground: "#d8dee9",
        card: "#3b4252",
        cardForeground: "#d8dee9",
        popover: "#3b4252",
        popoverForeground: "#d8dee9",
        primary: "#5e81ac",
        primaryForeground: "#eceff4",
        secondary: "#434c5e",
        secondaryForeground: "#d8dee9",
        muted: "#434c5e",
        mutedForeground: "#616e88",
        accent: "#4c566a",
        accentForeground: "#d8dee9",
        destructive: "#bf616a",
        border: "#4c566a",
        input: "#4c566a",
        ring: "#81a1c1",
        sidebar: "#3b4252",
        sidebarForeground: "#d8dee9",
        sidebarPrimary: "#5e81ac",
        sidebarPrimaryForeground: "#eceff4",
        sidebarAccent: "#434c5e",
        sidebarAccentForeground: "#d8dee9",
        sidebarBorder: "#4c566a",
        sidebarRing: "#81a1c1",
      },
      terminal: {
        background: "#2e3440",
        foreground: "#d8dee9",
        cursor: "#d8dee9",
        cursorAccent: "#2e3440",
        selection: "#4c566a",
        ansi: [
          "#3b4252", "#bf616a", "#a3be8c", "#ebcb8b",
          "#81a1c1", "#b48ead", "#88c0d0", "#e5e9f0",
          "#4c566a", "#bf616a", "#a3be8c", "#ebcb8b",
          "#81a1c1", "#b48ead", "#8fbcbb", "#eceff4",
        ],
      },
    },
    light: {
      colors: {
        background: "#c8d4e4",
        foreground: "#2e3440",
        card: "#b8c8dc",
        cardForeground: "#2e3440",
        popover: "#b8c8dc",
        popoverForeground: "#2e3440",
        primary: "#5e81ac",
        primaryForeground: "#eceff4",
        secondary: "#a8b8cc",
        secondaryForeground: "#2e3440",
        muted: "#b8c8dc",
        mutedForeground: "#4c566a",
        accent: "#98a8bc",
        accentForeground: "#2e3440",
        destructive: "#bf616a",
        border: "#98a8bc",
        input: "#98a8bc",
        ring: "#5e81ac",
        sidebar: "#b8c8dc",
        sidebarForeground: "#2e3440",
        sidebarPrimary: "#5e81ac",
        sidebarPrimaryForeground: "#eceff4",
        sidebarAccent: "#a8b8cc",
        sidebarAccentForeground: "#2e3440",
        sidebarBorder: "#98a8bc",
        sidebarRing: "#5e81ac",
      },
    },
  },
  editorTheme: {
    dark: "nord",
    light: "github-light",
  },
};
