import type { Theme } from "../types";

export const sage: Theme = {
  id: "sage",
  name: "Sage",
  description: "Muted forest greens, calm and focused",
  variants: {
    dark: {
      colors: {
        background: "#161d17",
        foreground: "#ccdbc5",
        card: "#1c2b1e",
        cardForeground: "#ccdbc5",
        popover: "#1c2b1e",
        popoverForeground: "#ccdbc5",
        primary: "#7cb87a",
        primaryForeground: "#161d17",
        secondary: "#243327",
        secondaryForeground: "#ccdbc5",
        muted: "#243327",
        mutedForeground: "#7d9b7a",
        accent: "#2c3d2c",
        accentForeground: "#ccdbc5",
        destructive: "#c0392b",
        border: "#2c3d2c",
        input: "#2c3d2c",
        ring: "#7cb87a",
        sidebar: "#1c2b1e",
        sidebarForeground: "#ccdbc5",
        sidebarPrimary: "#7cb87a",
        sidebarPrimaryForeground: "#161d17",
        sidebarAccent: "#243327",
        sidebarAccentForeground: "#ccdbc5",
        sidebarBorder: "#2c3d2c",
        sidebarRing: "#7cb87a",
      },
    },
    light: {
      colors: {
        background: "#c0d4bc",
        foreground: "#2c3d2c",
        card: "#aec4aa",
        cardForeground: "#2c3d2c",
        popover: "#aec4aa",
        popoverForeground: "#2c3d2c",
        primary: "#558b52",
        primaryForeground: "#f0f5ef",
        secondary: "#9ab498",
        secondaryForeground: "#2c3d2c",
        muted: "#a8bca6",
        mutedForeground: "#4d6a4a",
        accent: "#88a886",
        accentForeground: "#2c3d2c",
        destructive: "#c0392b",
        border: "#88a886",
        input: "#88a886",
        ring: "#558b52",
        sidebar: "#aec4aa",
        sidebarForeground: "#2c3d2c",
        sidebarPrimary: "#558b52",
        sidebarPrimaryForeground: "#f0f5ef",
        sidebarAccent: "#9ab498",
        sidebarAccentForeground: "#2c3d2c",
        sidebarBorder: "#88a886",
        sidebarRing: "#558b52",
      },
    },
  },
};
