import type { Theme } from "../types";

export const tide: Theme = {
  id: "tide",
  name: "Tide",
  description: "Deep slate-teal, like the ocean at dusk",
  variants: {
    dark: {
      colors: {
        background: "#121c20",
        foreground: "#b8d8de",
        card: "#172128",
        cardForeground: "#b8d8de",
        popover: "#172128",
        popoverForeground: "#b8d8de",
        primary: "#5e9eb0",
        primaryForeground: "#121c20",
        secondary: "#1e3038",
        secondaryForeground: "#b8d8de",
        muted: "#1e3038",
        mutedForeground: "#6a9faa",
        accent: "#243840",
        accentForeground: "#b8d8de",
        destructive: "#c0392b",
        border: "#243840",
        input: "#243840",
        ring: "#5e9eb0",
        sidebar: "#172128",
        sidebarForeground: "#b8d8de",
        sidebarPrimary: "#5e9eb0",
        sidebarPrimaryForeground: "#121c20",
        sidebarAccent: "#1e3038",
        sidebarAccentForeground: "#b8d8de",
        sidebarBorder: "#243840",
        sidebarRing: "#5e9eb0",
      },
    },
    light: {
      colors: {
        background: "#b8d4dc",
        foreground: "#1e3038",
        card: "#a4c4ce",
        cardForeground: "#1e3038",
        popover: "#a4c4ce",
        popoverForeground: "#1e3038",
        primary: "#2c7a8e",
        primaryForeground: "#eef5f7",
        secondary: "#8eb0bc",
        secondaryForeground: "#1e3038",
        muted: "#9cbac6",
        mutedForeground: "#3a6878",
        accent: "#78a0ae",
        accentForeground: "#1e3038",
        destructive: "#c0392b",
        border: "#78a0ae",
        input: "#78a0ae",
        ring: "#2c7a8e",
        sidebar: "#a4c4ce",
        sidebarForeground: "#1e3038",
        sidebarPrimary: "#2c7a8e",
        sidebarPrimaryForeground: "#eef5f7",
        sidebarAccent: "#8eb0bc",
        sidebarAccentForeground: "#1e3038",
        sidebarBorder: "#78a0ae",
        sidebarRing: "#2c7a8e",
      },
    },
  },
};
