name: Submit to Winget (first-time)

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: windows-latest
    steps:
      - name: Install wingetcreate
        run: winget install Microsoft.WingetCreate --silent --accept-package-agreements --accept-source-agreements

      - name: Submit new package to winget-pkgs
        run: |
          wingetcreate new `
            https://github.com/cLLeB/gear/releases/download/v0.1.1/Gear_0.1.1_x64_en-US.msi `
            --token ${{ secrets.WINGET_TOKEN }} `
            --no-open
